server:
  port: 8082

spring:
  application:    name: department-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: "377040"
      database: DepartmentDB

eureka:  client:    service-url:      defaultZone: http://localhost:9001/eureka