server:
  port: 8083

spring:
  application:    name: organization-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: "377040"
      database: OrganizationDB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka      